services:
  mongo:
    image: mongo:7
    container_name: holidays-mongo
    ports:
      - "27017:27017"

  holidays-api-service:
    build: ./services/holidays-api-service
    container_name: holidays-api-service
    depends_on:
      - mongo
    environment:
      - CONFIG_PATH=/app/config/config.docker.yaml
    ports:
      - "8081:8081"

  holidays-bff-service:
    build: ./services/holidays-bff-service
    container_name: holidays-bff-service
    depends_on:
      - holidays-api-service
    environment:
      - CONFIG_PATH=/app/config/config.docker.yaml
    ports:
      - "8080:8080"

  holidays-calculator-service:
    build: ./services/holidays-calculator-service
    container_name: holidays-calculator-service
    depends_on:
      - holidays-api-service
    environment:
      - CONFIG_PATH=/app/config/config.docker.yaml
    ports:
      - "8082:8082"

